In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("AmesHousing.csv")

In [4]:
df.head()

,Order,PID,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Alley,Lot Shape,Land Contour,...,Pool Area,Pool QC,Fence,Misc Feature,Misc Val,Mo Sold,Yr Sold,Sale Type,Sale Condition,SalePrice
0,1,526301100,20,RL,141.0,31770,Pave,NaN,IR1,Lvl,...,0,NaN,NaN,NaN,0,5,2010,WD,Normal,215000
1,2,526350040,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,...,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal,105000
2,3,526351010,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,...,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal,172000
3,4,526353030,20,RL,93.0,11160,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,244000
4,5,527105010,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,...,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal,189900

In [5]:
df.shape

(2930, 82)

In [6]:
df.size

240260

In [7]:
df.columns

Index(['Order', 'PID', 'MS SubClass', 'MS Zoning', 'Lot Frontage', 'Lot Area',
       'Street', 'Alley', 'Lot Shape', 'Land Contour', 'Utilities',
       'Lot Config', 'Land Slope', 'Neighborhood', 'Condition 1',
       'Condition 2', 'Bldg Type', 'House Style', 'Overall Qual',
       'Overall Cond', 'Year Built', 'Year Remod/Add', 'Roof Style',
       'Roof Matl', 'Exterior 1st', 'Exterior 2nd', 'Mas Vnr Type',
       'Mas Vnr Area', 'Exter Qual', 'Exter Cond', 'Foundation', 'Bsmt Qual',
       'Bsmt Cond', 'Bsmt Exposure', 'BsmtFin Type 1', 'BsmtFin SF 1',
       'BsmtFin Type 2', 'BsmtFin SF 2', 'Bsmt Unf SF', 'Total Bsmt SF',
       'Heating', 'Heating QC', 'Central Air', 'Electrical', '1st Flr SF',
       '2nd Flr SF', 'Low Qual Fin SF', 'Gr Liv Area', 'Bsmt Full Bath',
       'Bsmt Half Bath', 'Full Bath', 'Half Bath', 'Bedroom AbvGr',
       'Kitchen AbvGr', 'Kitchen Qual', 'TotRms AbvGrd', 'Functional',
       'Fireplaces', 'Fireplace Qu', 'Garage Type', 'Garage Yr Blt',
       'Garage Finish', 'Garage Cars', 'Garage Area', 'Garage Qual',
       'Garage Cond', 'Paved Drive', 'Wood Deck SF', 'Open Porch SF',
       'Enclosed Porch', '3Ssn Porch', 'Screen Porch', 'Pool Area', 'Pool QC',
       'Fence', 'Misc Feature', 'Misc Val', 'Mo Sold', 'Yr Sold', 'Sale Type',
       'Sale Condition', 'SalePrice'],
      dtype='object')

In [8]:
df.drop(columns=["Order", "PID"], inplace=True)

In [10]:
# Delete duplicate values or rows

In [11]:
before = len(df)
df.drop_duplicates(inplace=True)
print(f"Duplicates removed: {before - len(df)}")

Duplicates removed: 0

In [12]:
df.drop(columns=["Utilities", "Street"], inplace=True) #"AllPub" in  of rows; Street is "Pave" creates noise

In [13]:
df.shape

(2930, 78)

In [14]:
df["Garage Yr Blt"].unique

<bound method Series.unique of 0       1960.0
1       1961.0
2       1958.0
3       1968.0
4       1997.0
         ...
2925    1984.0
2926    1983.0
2927       NaN
2928    1975.0
2929    1993.0
Name: Garage Yr Blt, Length: 2930, dtype: float64>

In [15]:
df['Garage Yr Blt'].sort_values(ascending=False).head(5)

2260    2207.0
45      2010.0
17      2010.0
38      2010.0
316     2010.0
Name: Garage Yr Blt, dtype: float64

In [16]:
df["Garage Yr Blt"] = df["Garage Yr Blt"].replace(2207, 2007)

# FIX Dtypes

In [17]:
df.dtypes

MS SubClass         int64
MS Zoning          object
Lot Frontage      float64
Lot Area            int64
Alley              object
                   ...
Mo Sold             int64
Yr Sold             int64
Sale Type          object
Sale Condition     object
SalePrice           int64
Length: 78, dtype: object

In [19]:
df["MS SubClass"] = df["MS SubClass"].astype(str) ## to avoid category

In [20]:
int_year_cols = ["Year Built", "Year Remod/Add", "Yr Sold", "Mo Sold"]
df[int_year_cols] = df[int_year_cols].astype(int)

### Handle Missing Values In Categorical columns

In [23]:
categorical_none_cols = ["Pool QC", "Misc Feature", "Alley", "Fence","Fireplace Qu","Mas Vnr Type","Garage Type", "Garage Finish", "Garage Qual", "Garage Cond",
"Bsmt Qual", "Bsmt Cond", "Bsmt Exposure",
    "BsmtFin Type 1", "BsmtFin Type 2",
] ## for categorical filled with none

In [24]:
df[categorical_none_cols] = df[categorical_none_cols].fillna("None")

### Handle Missing Values In Numerical columns

In [26]:
zero_fill_cols = [
    "BsmtFin SF 1", "BsmtFin SF 2", "Bsmt Unf SF", "Total Bsmt SF",
    "Bsmt Full Bath", "Bsmt Half Bath",
    "Garage Cars", "Garage Area",
]
df[zero_fill_cols] = df[zero_fill_cols].fillna(0)

In [27]:
df["Mas Vnr Area"] = df["Mas Vnr Area"].fillna(0)

In [28]:
df["Garage Yr Blt"] = df["Garage Yr Blt"].fillna(df["Year Built"]) ## garage ta house build hune year mei built va hunxa so

In [29]:
df["Lot Frontage"].describe()

count    2440.000000
mean       69.224590
std        23.365335
min        21.000000
25%        58.000000
50%        68.000000
75%        80.000000
max       313.000000
Name: Lot Frontage, dtype: float64

In [30]:
## checking skewness to whether use mean or median

In [32]:
df["Lot Frontage"].skew()

np.float64(1.499067354883421)

In [33]:
# since it is right skewed there are outliers so use median

In [34]:
nbhd_median = df.groupby("Neighborhood")["Lot Frontage"].median().sort_values()

In [35]:
nbhd_median

Neighborhood
BrDale     21.0
MeadowV    21.0
Blueste    24.0
NPkVill    24.0
Greens     40.0
Blmngtn    43.0
BrkSide    51.0
SWISU      60.0
IDOTRR     60.0
StoneBr    60.0
OldTown    60.0
Gilbert    64.0
Edwards    65.0
SawyerW    67.0
Crawfor    70.0
CollgCr    70.0
Sawyer     72.0
Somerst    72.5
NAmes      73.0
Mitchel    74.0
NWAmes     80.0
Veenker    80.0
ClearCr    80.5
Timber     82.0
NoRidge    89.0
NridgHt    92.0
GrnHill     NaN
Landmrk     NaN
Name: Lot Frontage, dtype: float64

In [36]:
global_median = df["Lot Frontage"].median()  
df["Lot Frontage"] = df["Lot Frontage"].fillna(global_median)

In [37]:
df.isnull().sum()

MS SubClass       0
MS Zoning         0
Lot Frontage      0
Lot Area          0
Alley             0
                 ..
Mo Sold           0
Yr Sold           0
Sale Type         0
Sale Condition    0
SalePrice         0
Length: 78, dtype: int64

In [44]:
df['Electrical'].isnull().sum()

np.int64(1)

In [46]:
df["Electrical"] = df["Electrical"].fillna(df["Electrical"].mode()[0])

In [47]:
df['Electrical'].isnull().sum()

np.int64(0)

### Removing Whitespaces in Strings

In [53]:
str_cols = df.select_dtypes(include=["object"]).columns ## includes the col which are object 
df[str_cols] = df[str_cols].apply(lambda col: col.str.strip())

In [54]:
cat_cols = df.select_dtypes(include=["object"]).columns
df[cat_cols] = df[cat_cols].astype("category") ## change it back to categorical data type

In [55]:
df.shape

(2930, 78)

In [56]:
df.isnull().sum().sum()

np.int64(0)

In [57]:
df.dtypes.value_counts()

int64       25
float64     11
category     5
category     3
category     2
category     1
category     1
category     1
category     1
category     1
category     1
category     1
category     1
category     1
category     1
category     1
category     1
category     1
category     1
category     1
category     1
category     1
category     1
category     1
category     1
category     1
category     1
category     1
category     1
category     1
category     1
category     1
category     1
category     1
category     1
category     1
category     1
Name: count, dtype: int64

In [58]:
df.dtypes.astype(str).value_counts()

category    42
int64       25
float64     11
Name: count, dtype: int64

In [59]:
df.head()

,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Alley,Lot Shape,Land Contour,Lot Config,Land Slope,Neighborhood,...,Pool Area,Pool QC,Fence,Misc Feature,Misc Val,Mo Sold,Yr Sold,Sale Type,Sale Condition,SalePrice
0,20,RL,141.0,31770,None,IR1,Lvl,Corner,Gtl,NAmes,...,0,None,None,None,0,5,2010,WD,Normal,215000
1,20,RH,80.0,11622,None,Reg,Lvl,Inside,Gtl,NAmes,...,0,None,MnPrv,None,0,6,2010,WD,Normal,105000
2,20,RL,81.0,14267,None,IR1,Lvl,Corner,Gtl,NAmes,...,0,None,None,Gar2,12500,6,2010,WD,Normal,172000
3,20,RL,93.0,11160,None,Reg,Lvl,Corner,Gtl,NAmes,...,0,None,None,None,0,4,2010,WD,Normal,244000
4,60,RL,74.0,13830,None,IR1,Lvl,Inside,Gtl,Gilbert,...,0,None,MnPrv,None,0,3,2010,WD,Normal,189900